services:
  mongo:
    image: mongo:4.4.6
    restart: unless-stopped
    ports:
      - 27037:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: os.environ.get(username)
      MONGO_INITDB_ROOT_PASSWORD: os.environ.get(mongo_pass)

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8031:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: os.environ.get(username)
      ME_CONFIG_MONGODB_ADMINPASSWORD: os.environ.get(mongo_pass)
      ME_CONFIG_MONGODB_URL: mongodb://os.environ.get(username):os.environ.get(mongo_pass)@mongo:27017/

  backend:
    build: .
    ports:
      - 8090:8090
    volumes:
      - .:/education_press

    environment:
      PYTHONUNBUFFERED: 1
      TZ: Europe/Moscow

    logging:
      options:
        max-size: 50m
    depends_on:
      - mongo

    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8090"
    restart: unless-stopped

